apiVersion: batch/v1
kind: Job
metadata:
  name: neonvm-migration-loadtest
spec:
  backoffLimit: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neonvm-migration-loadtest
    spec:
      serviceAccountName: neonvm-migration-loadtest
      restartPolicy: Never
      containers:
      - name: loadtest
        image: cicdteam/neonvm-migration-loadtest:latest
        imagePullPolicy: Always
        args:
        - -vm-count=100
        - -duration=3600
        - -autoscale=false
        ports:
        - name: metrics
          containerPort: 9090
