apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: neonvm-migration-loadtest
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neonvm-migration-loadtest
  podMetricsEndpoints:
  - port: metrics
    interval: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: neonvm-pg
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: NeonVM
  podMetricsEndpoints:
  - port: pg-metrics
    metricRelabelings:
    - action: keep
      regex: pg_up|pg_stat_activity_count|pg_stat_database_xact_commit|pg_database_size_bytes
      sourceLabels:
      - __name__
