{
 "title": "Load Test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "MAx Pods Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(kube_pod_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max NeonVM Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{created_by_kind=~\"Virtual.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per second (summary)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "round(sum(rate(pg_stat_database_xact_commit{datname=\"bench\"}[$__rate_interval])))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Running postgres servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "sum(pg_up)", "legendFormat": "up" }
   ]
  },
  {
   "title": "Running pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"runner\"})",
     "legendFormat": "runner"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"pgbench\"})",
     "legendFormat": "pgbench"
    },
    {
     "expr": "sum(kube_pod_info{created_by_kind=\"VirtualMachineMigration\"})",
     "legendFormat": "target runner"
    }
   ]
  },
  {
   "title": "Completed pods (bugs?)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\",pod=~\"vm.*\"})",
     "legendFormat": "Completed pods"
    }
   ]
  },
  {
   "title": "NoenVM Controller: Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"neonvm-controller-metrics-service\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pod Start Duration (0.95 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kubelet_pod_start_duration_seconds_bucket{job=\"kubelet\", metrics_path=\"/metrics\"}[$__rate_interval])) by (le))",
     "legendFormat": "0.95 percentile"
    },
    {
     "expr": "max(rate(kubelet_pod_start_duration_seconds_sum{job=\"kubelet\", metrics_path=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "NoenVM Controller: Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}