apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: neonvm-pg
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: NeonVM
  podMetricsEndpoints:
  - port: pg-metrics

