apiVersion: batch/v1
kind: Job
metadata:
  name: neon-loadtest
spec:
  backoffLimit: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neon-loadtest
    spec:
      restartPolicy: Never
      containers:
      - name: loadtest
        image: cicdteam/neon-loadtest:latest
        imagePullPolicy: Always
        args:
        - -count=100
        - -duration=1h
        env:
        - name: NEON_API_KEY
          valueFrom:
            secretKeyRef:
              name: neon-loadtest
              key: apikey
