apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-re-terminator
  namespace: default
  labels:
    app.kubernetes.io/name: neon-re-terminator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neon-re-terminator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neon-re-terminator
    spec:
      serviceAccountName: neon-re-terminator
      enableServiceLinks: false
      terminationGracePeriodSeconds: 10
      containers:
      - name: neon-re-terminator
        image: cicdteam/neon-re-terminator:latest
        imagePullPolicy: Always
        args:
        - --zap-encoder=json
        resources: {}
