apiVersion: v1
kind: ServiceAccount
metadata:
  name: neon-re-terminator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neon-re-terminator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neon-re-terminator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neon-re-terminator
subjects:
- kind: ServiceAccount
  name: neon-re-terminator
  namespace: default
